name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D contribution graph

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate 3D profile contribution graph
        uses: yoshi389111/github-profile-3d-contrib@v0.9.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
